version: '2'
services:
  elasticsearch1:
    image: elasticsearch:2.4.1
    restart: always
    hostname: es1
    volumes:
      - ./es:/usr/share/elasticsearch/data 
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx4g"
    command: elasticsearch --discovery.zen.ping.unicast.hosts=es1 --script.inline=true --script.indexed=true --script.update=true --script.mapping=true --script.engine.groovy.indexed.aggs=true --script.engine.groovy.indexed.mapping=true --script.engine.groovy.indexed.search=true --script.engine.groovy.indexed.update=true --script.engine.groovy.indexed.plugin=true --script.engine.groovy.inline.aggs=true --script.engine.groovy.inline.mapping=true --script.engine.groovy.inline.search=true --script.engine.groovy.inline.update=true --script.engine.groovy.inline.plugin=true
    networks:
      nakisa:
        aliases:
          - es1

  slan:
    image: nakisa/leaseadministration:3.2-mysql-standalone-es
    restart: always
    environment:
      CATALINA_OPTS: "-Xms1g -Xmx4g"    
    depends_on:
      - elasticsearch1
      - slandb
    volumes:
      - ./data:/data
    networks:
      nakisa:
        aliases:
          - slan

  slandb:
    image: mysql:5.7
    restart: always
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: Nakisa_1
        MYSQL_DATABASE: slan
        #MYSQL_USER: root
        MYSQL_PASSWORD: Nakisa_1
    networks:
      nakisa:
        aliases:
          - slandb
# mysql --host=slandb --user=root --password=Nakisa_1 slan

  ngnix:  
    image: nginx:1.5.11
    restart: always
    depends_on:
      - slan
    volumes:
      - ./ngnix/:/etc/nginx/conf.d/external/
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "cat /etc/nginx/conf.d/external/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off; error_log /dev/stdout info;'"
    networks:
      nakisa:
        aliases:
          - nginx
networks:
  nakisa:
    driver: bridge
