version: '2'

services:
  elasticsearch1:
    image: elasticsearch:2.4.1
    hostname: es1
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    command: elasticsearch --discovery.zen.ping.unicast.hosts=es1
    volumes:
        - ./es:/usr/share/elasticsearch/data
    networks:
      nakisa:
        aliases:
          - es1
  hanelly1:
    image: nakisa/hanelly:2.2
    hostname: hanelly1
    ports:
      - "80:8080"
    volumes:
        - /usr/local/tomcat/webapps/hanelly
    depends_on:
      - elasticsearch1
      - hanelly-db
    networks:
      nakisa:
        aliases:
          - hanelly1
    environment:
        CATALINA_OPTS: "-Dcluster.standalone=false -Dcluster.discovery.file=WEB-INF/tcp.xml -Djgroups.bind_addr=hanelly1 -Djava.net.preferIPv4Stack=true -Xms2g -Xmx2g"
  hanelly-db:
    image: mysql:5.7
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: hanelly
        MYSQL_DATABASE: hanelly
        MYSQL_USER: hanelly
        MYSQL_PASSWORD: hanelly
    networks:
      nakisa:
        aliases:
          - hanelly-db

networks:
  nakisa:
    driver: bridge

