version: '3'

services:

  elasticsearch:
    image: elasticsearch:2.4.1
    volumes:
      - ./es:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx4g"
    command: elasticsearch --discovery.zen.ping.unicast.hosts=elasticsearch --script.inline=true --script.indexed=true --script.update=true --script.mapping=true --script.engine.groovy.indexed.aggs=true --script.engine.groovy.indexed.mapping=true --script.engine.groovy.indexed.search=true --script.engine.groovy.indexed.update=true --script.engine.groovy.indexed.plugin=true --script.engine.groovy.inline.aggs=true --script.engine.groovy.inline.mapping=true --script.engine.groovy.inline.search=true --script.engine.groovy.inline.update=true --script.engine.groovy.inline.plugin=true


  slan:
    image: nakisa/leaseadministration:3.2-mysql-standalone-es
    environment:
      CATALINA_OPTS: "-Xms1g -Xmx4g"
    depends_on:
      - elasticsearch
      - slandb
    volumes:
      - ./data:/data


  slandb:
    image: mysql:5.7
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: Nakisa_1
        MYSQL_DATABASE: slan
        #MYSQL_USER: root
        MYSQL_PASSWORD: Nakisa_1

# mysql --host=slandb --user=root --password=Nakisa_1 slan

  nginx:
    image: nginx
    depends_on:
      - slan
    volumes:
      - ./nginx/:/etc/nginx/conf.d/external/
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "cat /etc/nginx/conf.d/external/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off; error_log /dev/stdout info;'"
