version: '2'
services:
  elasticsearch1:
    image: elasticsearch:2.4.1
    hostname: es1
    volumes:
      - ./es:/usr/share/elasticsearch/data 
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx4g"
    command: elasticsearch --discovery.zen.ping.unicast.hosts=es1 --script.inline=true --script.indexed=true --script.update=true --script.mapping=true --script.engine.groovy.indexed.aggs=true --script.engine.groovy.indexed.mapping=true --script.engine.groovy.indexed.search=true --script.engine.groovy.indexed.update=true --script.engine.groovy.indexed.plugin=true --script.engine.groovy.inline.aggs=true --script.engine.groovy.inline.mapping=true --script.engine.groovy.inline.search=true --script.engine.groovy.inline.update=true --script.engine.groovy.inline.plugin=true
    networks:
      nakisa:
        aliases:
          - es1

  slan:
    image: nakisa/leaseadministration:3.2-mysql-standalone-es
    ports:
      - "80:8080" 
    environment:
      CATALINA_OPTS: "-Xms1g -Xmx4g"    
    depends_on:
      - elasticsearch1
      - slandb
    volumes:
      - ./data:/data
    networks:
      nakisa:
        aliases:
          - slan

  slandb:
    image: mysql:5.7
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: Nakisa_1
        MYSQL_DATABASE: slan
        #MYSQL_USER: root
        MYSQL_PASSWORD: Nakisa_1
    networks:
      nakisa:
        aliases:
          - slandb
# mysql --host=slandb --user=root --password=Nakisa_1 slan

networks:
  nakisa:
    driver: bridge
