version: '2'

services:
  elasticsearch1:
    image: elasticsearch:5.2.0
    hostname: es1
    environment:
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
    command: elasticsearch -Enetwork.host=es1 -Etransport.host=es1 -Ecluster.name=elasticsearch -Escript.inline=true -Escript.stored=true -Escript.max_compilations_per_minute=100000
    volumes:
        - ./es:/usr/share/elasticsearch/data
    networks:
      nakisa:
        aliases:
          - es1
  hanelly1:
    image: nakisa/hanelly:3.0.0-snapshot
    hostname: hanelly1
    volumes:
        - /usr/local/tomcat/webapps/hanelly
    depends_on:
      - elasticsearch1
      - hanelly-db
      - redis1
    networks:
      nakisa:
        aliases:
          - hanelly1
    environment:
        CATALINA_OPTS: "-Dredis.host=redis1 -Ddynamic.embedded=false -Ddynamic.host=es1 -Ddynamic.cluster=elasticsearch -Dcluster.standalone=false -Dcluster.discovery.file=WEB-INF/tcp.xml -Djgroups.bind_addr=hanelly1 -Djava.net.preferIPv4Stack=true -Xms6g -Xmx6g"
  hanelly-db:
    image: mysql:5.7
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: hanelly
        MYSQL_DATABASE: hanelly
        MYSQL_USER: hanelly
        MYSQL_PASSWORD: hanelly
    networks:
      nakisa:
        aliases:
          - hanelly-db
  redis1:
    image: redis:3.2.8
    volumes:
        - ./redis:/data
    networks:
      nakisa:
        aliases:
          - redis1
  nginx:  
    image: nginx
    depends_on:
      - hanelly1
    volumes:
      - ./nginx/:/etc/nginx/conf.d/external/
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "cat /etc/nginx/conf.d/external/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off; error_log /dev/stdout info;'"
    networks:
      nakisa:
        aliases:
          - nginx

networks:
  nakisa:
    driver: bridge

