version: '3'

services:
  elasticsearch:
    image: elasticsearch:2.4.1
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    command: elasticsearch --discovery.zen.ping.unicast.hosts=elasticsearch
    volumes:
        - ./es:/usr/share/elasticsearch/data
  hanelly:
    image: nakisa/hanelly:2.2
    volumes:
        - hanelly-data:/usr/local/tomcat/webapps/hanelly
        - ./agent:/usr/local/tomcat/agent/
    depends_on:
      - elasticsearch
      - hanelly-db
    environment:
        CATALINA_OPTS: "-javaagent:/usr/local/tomcat/agent/jmx_prometheus_javaagent-0.8.jar=4000:/usr/local/tomcat/agent/tomcat.yml -Ddynamic.embedded=false -Ddynamic.host=elasticsearch -Ddynamic.cluster=elasticsearch -Dcluster.standalone=false -Dcluster.discovery.file=WEB-INF/tcp.xml -Djgroups.bind_addr=hanelly -Djava.net.preferIPv4Stack=true -Xms2g -Xmx2g"
  hanelly-db:
    image: mysql:5.7
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: hanelly
        MYSQL_DATABASE: hanelly
        MYSQL_USER: hanelly
        MYSQL_PASSWORD: hanelly
  db-monitor:
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: "hanelly:hanelly@(hanelly-db:3306)/hanelly"
    depends_on:
      - hanelly-db
  cadvisor:
    image: google/cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
  ngnix:  
    image: nginx
    depends_on:
      - hanelly
    volumes:
      - ./ngnix/:/etc/nginx/conf.d/external/
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "cat /etc/nginx/conf.d/external/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off; error_log /dev/stdout info;'"
  prometheus:  
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana-startup:/var/lib/nakisa
      - ./grafana:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:/grafana"
      GF_SERVER_DOMAIN: "grafana"
    entrypoint: bash /var/lib/nakisa/setup.sh


volumes:
  hanelly-data:
