version: '2'

services:
  elasticsearch1:
    image: elasticsearch:5.2.0
    restart: always
    hostname: es1
    environment:
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
    command: elasticsearch -Enetwork.host=es1 -Etransport.host=es1 -Ecluster.name=elasticsearch -Escript.inline=true -Escript.stored=true -Escript.max_compilations_per_minute=100000
    volumes:
        - ./es:/usr/share/elasticsearch/data
    networks:
      nakisa:
        aliases:
          - es1
  hanelly:
    image: nakisa/hanelly:3.0.0-snapshot
    restart: always
    hostname: hanelly
    ports:
        - "80:8080"
    volumes:
        - /usr/local/tomcat/webapps/hanelly
    depends_on:
      - elasticsearch1
      - hanelly-db
      - redis1
    networks:
      nakisa:
        aliases:
          - hanelly
    environment:
        CATALINA_OPTS: "-Dsecurity.preventcsrf=true -Dnak.cookie.useHttpOnly=true -Dnak.cookie.useSecure=true -Dredis.host=redis1 -Ddynamic.embedded=false -Ddynamic.host=es1 -Ddynamic.cluster=elasticsearch -Dcluster.standalone=false -Dcluster.discovery.file=WEB-INF/tcp.xml -Djgroups.bind_addr=hanelly -Djava.net.preferIPv4Stack=true -Xms4g -Xmx4g"
  hanelly-db:
    image: mysql:5.7
    restart: always
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: hanelly
        MYSQL_DATABASE: hanelly
        MYSQL_USER: hanelly
        MYSQL_PASSWORD: hanelly
    networks:
      nakisa:
        aliases:
          - hanelly-db
  redis1:
    image: redis:3.2.8
    restart: always
    volumes:
        - ./redis:/data
    networks:
      nakisa:
        aliases:
          - redis1

networks:
  nakisa:
    driver: bridge

