version: '3'

services:
  apache-shib:
    image: nakisa/apache:2.4-shib
    volumes: 
      - ./apache-ssl:/etc/apache2/ssl
      - ./apache-conf:/etc/apache2/sites-enabled
      - ./apache-logs:/var/log/apache2
      - ./apache-shib:/usr/local/shibboleth
    ports:
      - "80:80"
      - "443:443"
